= Vert.x Http Proxy
:toc: left

Vert.x Http Proxy is a reverse proxy based on Vert.x, it aims to implement reusable reverse proxy logic to focus on
higher concerns.

WARNING: This module has _Tech Preview_ status, this means the API can change between versions.

== Using Vert.x Http Proxy

To use Vert.x Http Proxy, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-http-proxy</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'io.vertx:vertx-http-proxy:${maven.version}'
}
----

== Reverse proxy server

In order to accomplish a reverse proxy with Vert.x Http Proxy you need the following:

1. *Proxy Server* that handles user-agent requests and forward them to the *origin server*
2. *Origin Server* that handles requests from the *proxy server* and respond accordingly

You can create a *proxy server* that listens to port `8080` and implement reverse proxy logic

[source,java]
----
{@link examples.HttpProxyExamples#proxy}
----

All user-agent requests are forwarded to the *origin server* conveniently.

=== Origin server routing

You can create a proxy that forwards all the traffic to a single server like seen before

You can set an origin selector to route the traffic to a given server

[source,java]
----
{@link examples.HttpProxyExamples#originSelector}
----

You can set a function to create the client request to the origin server for ultimate flexibility

[source,java]
----
{@link examples.HttpProxyExamples#originRequestProvider}
----

=== Headers forwarding

End-to-end headers are forwarded by the proxy, hop-by-hop headers are ignored.

==== Request authority

As a transparent proxy, the request authority (`Host` header for HTTP/1.1, `:authority` pseudo header for HTTP/2) is preserved.

You can override the request authority

[source,java]
----
{@link examples.HttpProxyExamples#overrideAuthority}
----

When the request authority is overridden, the `x-forwarded-host` header is set on the request to the origin server with the original authority value.

WARNING: changing the request authority can have undesirable side effects and can affect the proxied web server that might
rely on the original request authority to handle cookies, URL redirects and such.

=== WebSockets

The proxy supports WebSocket by default.

WebSocket handshake requests  are forwarded to the origin server (including the `connection` header)  and the handshake
happens between the user agent and the origin server.

You can configure WebSocket support with {@link io.vertx.httpproxy.ProxyOptions#setSupportWebSocket}.

=== Proxy caching

By default the proxy does not cache response and ignores most cache directives, you can enable caching by setting the cache options.

[source,java]
----
{@link examples.HttpProxyExamples#cacheConfig}
----

=== Proxy interception

Interception is a powerful way to extend the proxy withg new features.

You can implement {@link io.vertx.httpproxy.ProxyInterceptor#handleProxyRequest} to perform any operation on the proxy request

[source,java]
----
{@link examples.HttpProxyExamples#inboundInterceptor}
----

Likewise with the proxy response

[source,java]
----
{@link examples.HttpProxyExamples#outboundInterceptor}
----

Interceptors will not apply to WebSocket handshake packets by default. While in some use cases (e.g. changing the WebSocket request path), you can overwrite {@link io.vertx.httpproxy.ProxyInterceptor#allowApplyToWebSocket} method to allow interceptors apply to WebSocket.

==== Body filtering

You can filter body by simply replacing the original {@link io.vertx.httpproxy.Body} with a new one

[source,java]
----
{@link examples.HttpProxyExamples#bodyFilter}
----

==== Interception control

{@link io.vertx.httpproxy.ProxyContext#sendRequest} and {@link io.vertx.httpproxy.ProxyContext#sendResponse} continue the
current interception chain and then send the result to the origin server or the user-agent.

You can change the control, e.g you can send a response immediately to the user-agent without even requesting the origin server

[source,java]
----
{@link examples.HttpProxyExamples#immediateResponse}
----

==== Header interceptor

You can apply header interceptors to change headers from the request and response with common operations:

[source,java]
----
{@link examples.HttpProxyExamples#headerInterceptorFilter}
----

Check out the {@link io.vertx.httpproxy.interceptors.HeadersInterceptor} class for details about the available methods.

==== Query interceptor

You can use query interceptors to update or remove the query parameters:

[source,java]
----
{@link examples.HttpProxyExamples#queryInterceptorAdd}
----

You can also refer to {@link io.vertx.httpproxy.interceptors.QueryInterceptor} for more information.

==== Body interceptor

You can use body interceptor to create body transformations for common data types, like {@link io.vertx.core.json.JsonObject}:

[source,java]
----
{@link examples.HttpProxyExamples#bodyInterceptorJson}
----

Please check the {@link io.vertx.httpproxy.interceptors.BodyTransformer} for other supported transformations.

==== WebSocket interceptor

You can use WebSocket interceptor to wrap an interceptor to let it allow WebSocket handling:

[source,java]
----
{@link examples.HttpProxyExamples#webSocketInterceptorPath}
----

